[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "nudenet>=3.4.2",
    "numpy>=2.2.6",
    "pillow>=11.2.1",
]
